(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const P='dp3:'+((window.DP_USER&&window.DP_USER.id)||'guest')+':';let flashTimer;const save=(k,v)=>{localStorage.setItem(P+k,typeof v==='string'?v:JSON.stringify(v));const x=$('#saved');x.classList.add('show');clearTimeout(flashTimer);flashTimer=setTimeout(()=>x.classList.remove('show'),650)};const get=(k,d='')=>{const v=localStorage.getItem(P+k);if(v===null)return d;return v};const json=(k,d)=>{try{return JSON.parse(get(k,''))||d}catch{return d}};const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function go(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===id));$('#tabs').classList.remove('open');scrollTo({top:0,behavior:'smooth'})}$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#moreBtn').onclick=()=>$('#tabs').classList.toggle('open');
$$('[data-field]').forEach(el=>{el.value=get(el.dataset.field,'');el.oninput=()=>save(el.dataset.field,el.value);el.onchange=el.oninput});const now=new Date();$('#lessonDate').value=get('lesson-date',iso(now));$('#lessonDate').onchange=()=>save('lesson-date',$('#lessonDate').value);
let month=new Date(2026,8,1),selected='';function renderCal(){const y=month.getFullYear(),m=month.getMonth();$('#monthLabel').textContent=month.toLocaleDateString('en-GB',{month:'long',year:'numeric'});let h=['M','T','W','T','F','S','S'].map(x=>`<div class="dow">${x}</div>`).join('');const blank=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();h+='<div></div>'.repeat(blank);for(let d=1;d<=days;d++){const k=iso(new Date(y,m,d)),n=get('cal:'+k,'');h+=`<button class="date ${k===iso(now)?'today':''} ${k===selected?'selected':''}" data-date="${k}"><b>${d}</b>${n?`<small>• ${n.slice(0,20)}</small>`:''}</button>`}$('#calendar').innerHTML=h;$$('[data-date]').forEach(b=>b.onclick=()=>selectDate(b.dataset.date))}function selectDate(k){selected=k;$('#selectedDate').value=k;$('#calendarNote').value=get('cal:'+k,'');renderCal()}$('#prevMonth').onclick=()=>{month.setMonth(month.getMonth()-1);renderCal()};$('#nextMonth').onclick=()=>{month.setMonth(month.getMonth()+1);renderCal()};$('#selectedDate').onchange=()=>selectDate($('#selectedDate').value);$('#calendarNote').oninput=()=>{if(selected){save('cal:'+selected,$('#calendarNote').value);renderCal()}};renderCal();
let monday=new Date(now);monday.setHours(12,0,0,0);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));function renderWeek(){const end=new Date(monday);end.setDate(end.getDate()+4);$('#weekLabel').textContent=`${monday.toLocaleDateString('en-GB',{day:'numeric',month:'short'})} – ${end.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}`;const names=['Monday','Tuesday','Wednesday','Thursday','Friday'];$('#weekGrid').innerHTML=names.map((n,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);const k='week:'+iso(monday)+':'+i;return `<div class="day"><h3>${n}<br>${d.toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</h3><textarea data-w="${k}" placeholder="Lessons, duties, reminders…"></textarea></div>`}).join('');$$('[data-w]').forEach(t=>{t.value=get(t.dataset.w,'');t.oninput=()=>save(t.dataset.w,t.value)})}$('#prevWeek').onclick=()=>{monday.setDate(monday.getDate()-7);renderWeek()};$('#nextWeek').onclick=()=>{monday.setDate(monday.getDate()+7);renderWeek()};renderWeek();
let classes=json('classes',[{id:Date.now(),name:'My Class',notes:'',pupils:[]}]),classId=Number(get('classId',classes[0]?.id||0));function current(){return classes.find(c=>c.id===classId)||classes[0]}function saveClasses(){save('classes',classes);save('classId',String(classId))}function renderClasses(){if(!classes.length){classes=[{id:Date.now(),name:'My Class',notes:'',pupils:[]}];classId=classes[0].id}$('#classSelect').innerHTML=classes.map(c=>`<option value="${c.id}">${esc(c.name||'Untitled class')}</option>`).join('');$('#classSelect').value=String(classId);const c=current();$('#className').value=c.name;$('#classNotes').value=c.notes;$('#pupilRows').innerHTML=c.pupils.map((p,i)=>`<tr><td><input data-pn="${i}" value="${esc(p.name)}"></td><td><input data-pi="${i}" value="${esc(p.info)}"></td><td><button class="rowdel" data-pdel="${i}">×</button></td></tr>`).join('');$$('[data-pn]').forEach(x=>x.oninput=()=>{current().pupils[+x.dataset.pn].name=x.value;saveClasses()});$$('[data-pi]').forEach(x=>x.oninput=()=>{current().pupils[+x.dataset.pi].info=x.value;saveClasses()});$$('[data-pdel]').forEach(x=>x.onclick=()=>{current().pupils.splice(+x.dataset.pdel,1);saveClasses();renderClasses()})}const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));$('#classSelect').onchange=()=>{classId=+$('#classSelect').value;saveClasses();renderClasses()};$('#className').oninput=()=>{current().name=$('#className').value;saveClasses();$('#classSelect').selectedOptions[0].textContent=$('#className').value||'Untitled class'};$('#classNotes').oninput=()=>{current().notes=$('#classNotes').value;saveClasses()};$('#addClass').onclick=()=>{const c={id:Date.now(),name:'New Class',notes:'',pupils:[]};classes.push(c);classId=c.id;saveClasses();renderClasses()};$('#deleteClass').onclick=()=>{if(classes.length>1&&confirm('Delete this class?')){classes=classes.filter(c=>c.id!==classId);classId=classes[0].id;saveClasses();renderClasses()}};$('#addPupil').onclick=()=>{current().pupils.push({name:'',info:''});saveClasses();renderClasses()};renderClasses();
function tableRecords(key,tbody,addBtn,cols){let arr=json(key,[]);function draw(){$(tbody).innerHTML=arr.map((r,i)=>`<tr>${cols.map((c,j)=>`<td><input type="${c.type||'text'}" data-rec="${i}:${j}" value="${esc(r[c.k]||'')}"></td>`).join('')}<td><button class="rowdel" data-rdel="${i}">×</button></td></tr>`).join('');$$('[data-rec]').forEach(x=>x.oninput=()=>{const[i,j]=x.dataset.rec.split(':').map(Number);arr[i][cols[j].k]=x.value;save(key,arr)});$$('[data-rdel]').forEach(x=>x.onclick=()=>{arr.splice(+x.dataset.rdel,1);save(key,arr);draw()})}$(addBtn).onclick=()=>{arr.push(Object.fromEntries(cols.map(c=>[c.k,''])));save(key,arr);draw()};draw()}tableRecords('readers','#readerRows','#addReader',[{k:'child'},{k:'book'},{k:'date',type:'date'},{k:'notes'}]);
let tasks=json('tasks',[]);function drawTasks(){if(!tasks.length)tasks=[{text:'',done:false}];$('#tasks').innerHTML=tasks.map((t,i)=>`<div class="task"><input type="checkbox" data-tcheck="${i}" ${t.done?'checked':''}><input type="text" data-ttext="${i}" value="${esc(t.text)}" placeholder="Add a task…"><button class="rowdel" data-tdel="${i}">×</button></div>`).join('');$$('[data-tcheck]').forEach(x=>x.onchange=()=>{tasks[+x.dataset.tcheck].done=x.checked;save('tasks',tasks)});$$('[data-ttext]').forEach(x=>x.oninput=()=>{tasks[+x.dataset.ttext].text=x.value;save('tasks',tasks)});$$('[data-tdel]').forEach(x=>x.onclick=()=>{tasks.splice(+x.dataset.tdel,1);save('tasks',tasks);drawTasks()})}$('#addTask').onclick=()=>{tasks.push({text:'',done:false});save('tasks',tasks);drawTasks()};drawTasks();
function cardRecords(key,list,btn,type){let arr=json(key,[]);function draw(){if(!arr.length)arr=[{}];$(list).innerHTML=arr.map((r,i)=>`<div class="paper record"><button class="removeRecord" data-delcard="${i}">×</button><div class="grid2"><label>Date<input type="date" data-card="${i}:date" value="${esc(r.date||'')}"></label><label>${type==='meeting'?'Type':'Course / Training'}<input data-card="${i}:title" value="${esc(r.title||'')}"></label></div><label>${type==='meeting'?'Key points':'Key learning'}<textarea data-card="${i}:notes}">${esc(r.notes||'')}</textarea></label><label>${type==='meeting'?'Actions / follow up':'How I will use this'}<textarea data-card="${i}:action">${esc(r.action||'')}</textarea></label></div>`).join('').replace(/data-card="(\d+):notes}"/g,'data-card="$1:notes"');$$('[data-card]').forEach(x=>x.oninput=()=>{const[i,k]=x.dataset.card.split(':');arr[+i][k]=x.value;save(key,arr)});$$('[data-delcard]').forEach(x=>x.onclick=()=>{arr.splice(+x.dataset.delcard,1);save(key,arr);draw()})}$(btn).onclick=()=>{arr.push({});save(key,arr);draw()};draw()}cardRecords('meetings','#meetingList','#addMeeting','meeting');cardRecords('cpd','#cpdList','#addCpd','cpd');

// --- secure account controls ---
const LS=localStorage;
const lockNow=$('#lockNow'); if(lockNow) lockNow.onclick=()=>window.DP_SIGN_OUT&&window.DP_SIGN_OUT();
const settingsSignOut=$('#settingsSignOut'); if(settingsSignOut) settingsSignOut.onclick=()=>window.DP_SIGN_OUT&&window.DP_SIGN_OUT();
const accountEmail=$('#accountEmail'); if(accountEmail&&window.DP_USER) accountEmail.textContent='Signed in as '+(window.DP_USER.email||'your account')+'.';
function syncClassSelectors(){['#assessClass','#seatClass'].forEach(sel=>{$(sel).innerHTML=classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$(sel).value=String(classId)})}function drawSeats(){const cid=+$('#seatClass').value||classId;let seats=json('seats:'+cid,Array.from({length:16},()=>''));$('#seatGrid').innerHTML=seats.map((v,i)=>`<div class="seat"><input data-seat="${i}" value="${esc(v)}" placeholder="Pupil"></div>`).join('');$$('[data-seat]').forEach(x=>x.oninput=()=>{seats[+x.dataset.seat]=x.value;save('seats:'+cid,seats)})}syncClassSelectors();$('#seatClass').onchange=drawSeats;$('#clearSeats').onclick=()=>{if(confirm('Clear this seating plan?')){save('seats:'+$('#seatClass').value,Array.from({length:16},()=>''));drawSeats()}};drawSeats();
// assessment + pastoral
let assessments=json('assessments',[]);function drawAssess(){const cid=+$('#assessClass').value||classId;const rows=assessments.map((r,i)=>[r,i]).filter(([r])=>r.classId===cid);$('#assessmentRows').innerHTML=rows.map(([r,i])=>`<tr>${['pupil','subject','current','target','note'].map(k=>`<td><input data-ass="${i}:${k}" value="${esc(r[k]||'')}"></td>`).join('')}<td><button class="rowdel" data-adel="${i}">×</button></td></tr>`).join('');$$('[data-ass]').forEach(x=>x.oninput=()=>{let[i,k]=x.dataset.ass.split(':');assessments[+i][k]=x.value;save('assessments',assessments)});$$('[data-adel]').forEach(x=>x.onclick=()=>{assessments.splice(+x.dataset.adel,1);save('assessments',assessments);drawAssess()})}$('#assessClass').onchange=drawAssess;$('#addAssessment').onclick=()=>{assessments.push({classId:+$('#assessClass').value,pupil:'',subject:'',current:'',target:'',note:''});save('assessments',assessments);drawAssess()};drawAssess();tableRecords('pastoral','#pastoralRows','#addPastoral',[{k:'date',type:'date'},{k:'child'},{k:'concern'},{k:'action'}]);
// backup controls
$('#exportBackup').onclick=()=>{const data={};for(let i=0;i<LS.length;i++){const k=LS.key(i);if(k.startsWith(P))data[k]=LS.getItem(k)}const blob=new Blob([JSON.stringify({product:'Daisy & Paws Digital Teacher Planner',version:4,exported:new Date().toISOString(),data},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Daisy-and-Paws-planner-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#restoreBackup').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const b=JSON.parse(await f.text());Object.entries(b.data||{}).forEach(([k,v])=>{if(k.startsWith(P))LS.setItem(k,v)});alert('Backup restored. The planner will reload.');location.reload()}catch{alert('That backup file could not be read.')}};
$('#eraseData').onclick=()=>{if(confirm('Erase ALL planner data on this device? This cannot be undone unless you have a backup.')){[...Array(LS.length)].map((_,i)=>LS.key(i)).filter(k=>k&&k.startsWith(P)).forEach(k=>LS.removeItem(k));location.reload()}};


// --- Commercial beta onboarding, personalisation, lesson library & search ---
const profile=json('profile',{});
const onboarding=$('#onboarding');
function applyProfile(){const pr=json('profile',{});const n=pr.name||'Teacher';const tn=$('#teacherName');if(tn)tn.textContent=n;}
applyProfile();
      const profileName=$('#profileName'),profileSchool=$('#profileSchool'),profileClass=$('#profileClass'),saveProfileBtn=$('#saveProfile');if(profileName)profileName.value=profile.name||'';if(profileSchool)profileSchool.value=profile.school||'';if(profileClass)profileClass.value=profile.className||'';if(saveProfileBtn)saveProfileBtn.onclick=()=>{const pr=json('profile',{});pr.name=profileName.value.trim()||'Teacher';pr.school=profileSchool.value.trim();pr.className=profileClass.value.trim();pr.setupComplete=true;save('profile',pr);applyProfile();alert('Profile saved ♡');};
if(!profile.setupComplete){onboarding.classList.remove('hidden');}
$('#finishSetup').onclick=()=>{const name=$('#setupName').value.trim()||'Teacher';const school=$('#setupSchool').value.trim();const mainClass=$('#setupClass').value.trim();const year=$('#setupYear').value;save('profile',{name,school,mainClass,year,setupComplete:true});if(mainClass&&classes.length===1&&classes[0].name==='My Class'){classes[0].name=mainClass;saveClasses();renderClasses();syncClassSelectors();}onboarding.classList.add('hidden');applyProfile();};

let templates=json('lessonTemplates',[]);
function lessonSnapshot(){return {id:Date.now(),title:(document.querySelector('[data-field="lesson-objective"]')?.value||'Untitled lesson').slice(0,80),className:document.querySelector('[data-field="lesson-class"]')?.value||'',objective:document.querySelector('[data-field="lesson-objective"]')?.value||'',success:document.querySelector('[data-field="lesson-success"]')?.value||'',vocab:document.querySelector('[data-field="lesson-vocab"]')?.value||'',resources:document.querySelector('[data-field="lesson-resources"]')?.value||'',next:document.querySelector('[data-field="lesson-next"]')?.value||''};}
function drawTemplates(){const box=$('#lessonTemplates');if(!box)return;box.innerHTML=templates.length?'<h3>Lesson library</h3>'+templates.map((t,i)=>`<div class="templateItem"><span><b>${esc(t.title)}</b><small>${esc(t.className)}</small></span><button class="secondary" data-loadtpl="${i}">Use</button><button class="rowdel" data-deltpl="${i}">×</button></div>`).join(''):'';$$('[data-loadtpl]').forEach(b=>b.onclick=()=>{const t=templates[+b.dataset.loadtpl];const map={'lesson-class':t.className,'lesson-objective':t.objective,'lesson-success':t.success,'lesson-vocab':t.vocab,'lesson-resources':t.resources,'lesson-next':t.next};Object.entries(map).forEach(([k,v])=>{const el=document.querySelector(`[data-field="${k}"]`);if(el){el.value=v;save('field:'+k,v)}});go('today')});$$('[data-deltpl]').forEach(b=>b.onclick=()=>{templates.splice(+b.dataset.deltpl,1);save('lessonTemplates',templates);drawTemplates()})}
$('#saveLessonTemplate').onclick=()=>{templates.push(lessonSnapshot());save('lessonTemplates',templates);drawTemplates();};
$('#duplicateLesson').onclick=()=>{const d=$('#lessonDate');if(d){let x=d.value?new Date(d.value+'T12:00:00'):new Date();x.setDate(x.getDate()+1);d.value=iso(x);d.dispatchEvent(new Event('change'));}alert('Lesson copied. Choose the new date and edit anything you need.');};
drawTemplates();

const searchOverlay=$('#searchOverlay'), searchInput=$('#globalSearch'), searchResults=$('#searchResults');
function openSearch(){searchOverlay.classList.remove('hidden');setTimeout(()=>searchInput.focus(),50)}
$('#openSearch').onclick=openSearch;$('#closeSearch').onclick=()=>searchOverlay.classList.add('hidden');
function collectSearch(){let out=[];const pr=json('profile',{});if(pr.school)out.push({page:'settings',title:'School',text:pr.school});classes.forEach(c=>{out.push({page:'classes',title:'Class',text:c.name+' '+(c.notes||'')});(c.pupils||[]).forEach(p=>out.push({page:'classes',title:'Pupil',text:(p.name||'')+' '+(p.info||'')}))});json('tasks',[]).forEach(t=>out.push({page:'todo',title:'To Do',text:t.text||''}));templates.forEach(t=>out.push({page:'today',title:'Lesson',text:[t.title,t.className,t.objective,t.success,t.vocab,t.resources].join(' ')}));['notes','wellbeing','term-objectives','term-topics','term-dates','term-notes','lesson-objective','lesson-success','lesson-reflection'].forEach(k=>{const v=get('field:'+k,get(k,''));if(v)out.push({page:k.startsWith('term')?'term':k.startsWith('lesson')?'today':k==='wellbeing'?'wellbeing':'notes',title:'Planner',text:v})});return out;}
searchInput.oninput=()=>{const q=searchInput.value.trim().toLowerCase();if(q.length<2){searchResults.innerHTML='<p class="gentle">Type at least 2 characters.</p>';return}const hits=collectSearch().filter(x=>x.text.toLowerCase().includes(q)).slice(0,30);searchResults.innerHTML=hits.length?hits.map((h,i)=>`<button class="searchHit" data-sh="${i}"><b>${esc(h.title)}</b><small>${esc(h.text.slice(0,150))}</small></button>`).join(''):'<p class="gentle">No matches found.</p>';$$('[data-sh]').forEach((b,i)=>b.onclick=()=>{searchOverlay.classList.add('hidden');go(hits[i].page)})};
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')searchOverlay.classList.add('hidden')});

if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol))navigator.serviceWorker.register('./sw.js').catch(()=>{});

// Pre-release 5 dashboard enhancements
const dd=document.querySelector('#dashDate'); if(dd){dd.textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());}
document.querySelectorAll('.miniTasks input').forEach((cb,i)=>{const k='dp3:dashTask:'+i;cb.checked=localStorage.getItem(k)==='1';cb.addEventListener('change',()=>localStorage.setItem(k,cb.checked?'1':'0'));});
})();
// Commercial Beta 2 — visible feature additions
const planningFile=$('#planningFile'); if(planningFile) planningFile.onchange=async()=>{const f=planningFile.files[0];if(!f)return;try{$('#planningPreview').value=await f.text()}catch(e){$('#planningPreview').value='This file needs the secure document importer planned for the production release.'}};
if($('#usePlanningImport')) $('#usePlanningImport').onclick=()=>{const v=$('#planningPreview').value.trim();if(!v)return alert('Choose a planning file first.');const el=document.querySelector('[data-field="term-notes"]');el.value=(el.value?el.value+'\n\n':'')+'IMPORTED SCHOOL PLANNING\n'+v;save('field:term-notes',el.value);alert('Imported into Termly Planning. Please review and edit before using it.')};
let seatLayout=get('seatLayout:'+classId,'rows');function applySeatLayout(){if(!$('#seatGrid'))return;$('#seatGrid').className='seats '+seatLayout;$$('[data-layout]').forEach(b=>b.classList.toggle('active',b.dataset.layout===seatLayout))}$$('[data-layout]').forEach(b=>b.onclick=()=>{seatLayout=b.dataset.layout;save('seatLayout:'+($('#seatClass').value||classId),seatLayout);applySeatLayout()});const oldSeatChange=$('#seatClass').onchange;$('#seatClass').onchange=()=>{if(oldSeatChange)oldSeatChange();seatLayout=get('seatLayout:'+$('#seatClass').value,'rows');applySeatLayout();drawSavedPlans()};
function drawSavedPlans(){if(!$('#savedSeatPlans'))return;const cid=+$('#seatClass').value||classId;const plans=json('seatPlans:'+cid,[]);$('#savedSeatPlans').innerHTML='<option value="">Saved arrangements…</option>'+plans.map((p,i)=>`<option value="${i}">${esc(p.name)}</option>`).join('')}
if($('#saveSeatPlan'))$('#saveSeatPlan').onclick=()=>{const cid=+$('#seatClass').value||classId;const name=$('#seatPlanName').value.trim()||'Seating plan';let plans=json('seatPlans:'+cid,[]);plans.push({name,layout:seatLayout,seats:json('seats:'+cid,[])});save('seatPlans:'+cid,plans);$('#seatPlanName').value='';drawSavedPlans()};if($('#savedSeatPlans'))$('#savedSeatPlans').onchange=()=>{const cid=+$('#seatClass').value||classId;const p=json('seatPlans:'+cid,[])[+$('#savedSeatPlans').value];if(!p)return;save('seats:'+cid,p.seats||[]);seatLayout=p.layout||'rows';save('seatLayout:'+cid,seatLayout);drawSeats();applySeatLayout()};applySeatLayout();drawSavedPlans();
if($('#applySchoolDay')){$('#dayStart').value=get('schoolDayStart','08:45');$('#dayEnd').value=get('schoolDayEnd','15:30');$('#slotLength').value=get('schoolSlot','60');$('#applySchoolDay').onclick=()=>{save('schoolDayStart',$('#dayStart').value);save('schoolDayEnd',$('#dayEnd').value);save('schoolSlot',$('#slotLength').value);alert('School-day settings saved. The next timetable engine will generate individual named periods and weekday variations from these settings.')};}


// --- Home dashboard: today's lesson ---
function updateHomeDashboard() {
  const box = document.querySelector('#todayLessons');
  if (!box) return;

  const today = new Date();
  const todayKey =
    today.getFullYear() + '-' +
    String(today.getMonth() + 1).padStart(2, '0') + '-' +
    String(today.getDate()).padStart(2, '0');

  const lessonDate = document.querySelector('#lessonDate')?.value || '';
  const lessonClass =
    document.querySelector('[data-field="lesson-class"]')?.value?.trim() || '';
  const objective =
    document.querySelector('[data-field="lesson-objective"]')?.value?.trim() || '';

  if (lessonDate === todayKey && (lessonClass || objective)) {
    box.innerHTML = `
      <div class="miniRow">
        <span class="timeTag">Today</span>
        <span>${lessonClass || objective || "Today's lesson"}</span>
        <button data-go="today">→</button>
      </div>
    `;
  } else {
    box.innerHTML = `
      <div class="miniRow">
        <span class="timeTag">Today</span>
        <span>No lesson planned yet</span>
        <button data-go="today">+</button>
      </div>
    `;
  }

  box.querySelectorAll('[data-go]').forEach(button => {
    button.onclick = () => {
      document.querySelectorAll('.page').forEach(page =>
        page.classList.toggle('active', page.id === button.dataset.go)
      );
      document.querySelectorAll('[data-go]').forEach(nav =>
        nav.classList.toggle('active', nav.dataset.go === button.dataset.go)
      );
    };
  });
}

setTimeout(updateHomeDashboard, 100);
